### PR TITLE
Add optional scroll listener

### PR DESCRIPTION
**Pull request by jayabrown**
Add optional function to be passed in that allows parent widget to listen to the scroll percentage

### CODE REVIEW

**Comment by jayabrown** [comment]
@paurakhsharma I'm not sure if this is the best way to do this.  But I just want to be able to listen to scroll position so I can do some layout adjustments in the parent widget (like show/hide app bar, for example, depending on user scroll).

**Comment by paurakhsharma** [comment]
Hey @jayabrown thank you for the PR.
I would suggest instead of passing in `scrollListener` callback what about we pass optional `ScrollController` just like in this PR: https://github.com/paurakhsharma/flutter_chord/pull/16

The original author seem to have abandoned this PR but you can take inspiration from you. Please only make changes regarding ScrollController and not bottom and top padding related changes. 

I believe that would solve what your are trying to achieve?

**Comment by jayabrown** [comment]
Ok yes, that method is better.

**Review by paurakhsharma — APPROVED** [review]
Thank you so much!

**Pull request merged**
