### PR TITLE
If verse number is present carry it next line 

### PR DESCRIPTION
**Pull request by jeremiahlukus**
i changed the example to 
```
[C]In the streets our, [F]hands are lifting
[Am]As we lose our, [G]inhibition
[C]Celebration, [F]its around us
[Am]Every nation, [G]all around us

1
[C]Give me Freedom, [F]Give me fire
[Am]Give me reason, [G]Take me higher
[C]See the champions [F], Take the field now
[Am]Unify us, [G]make us feel proud
```

if the verse number is present move it to the side.
linked to https://github.com/paurakhsharma/flutter_chord/issues/21

This does add a bit of padding to the side which i like, I wrap all of this in a if statement and pass in a new bool to LyricsRenderer called `formatVerse` if this is a change you want. 

Screenshot 2023-10-31 at 8 53 50 AM

### CODE REVIEW

**Comment by jeremiahlukus** [comment]
Going to close this i think this might too custom to be in this package.

**Comment by paurakhsharma** [comment]
Yes, I think this is too custom to be in a package. We can achieve this using the directive I mentioned in the issue.
For your app maybe it's better if you add the intermediary step to convert your carry line to directive before passing it to LyricsRenderer, or maybe run a migration on your lyrics set if it is an asset, but if it comes from the server it might be little more tricky.

**Comment by jeremiahlukus** [comment]
I agree, for now I'll keep pulling from my fork when I have time to reformat all my lyrics I'll add this. 
Other than that if i find more bugs I'll submit a PR.

**Comment by paurakhsharma** [comment]
Great, thank you so much.

**Pull request closed without merging**
